coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
memory.heap-headroom-per-node=14GB
query.max-memory=28GB
query.max-memory-per-node=14GB
query.max-total-memory=56GB
query.max-stage-count=200
discovery.uri=http://localhost:8080
