import pyarrow as pa
import pytest
from hyperstreamdb import Table

@pytest.fixture
def dbt_edge_table(tmpdir):
    uri = str(tmpdir.join("dbt_edges"))
    schema = pa.schema([
        ("source", pa.uint64()),
        ("target", pa.uint64()),
        ("relation", pa.string()),
        ("weight", pa.float64()),
    ])
    table = Table.create_edge_table(uri, schema)
    data = pa.Table.from_arrays([
        pa.array([1, 2, 2, 3, 4], type=pa.uint64()),
        pa.array([2, 3, 4, 4, 1], type=pa.uint64()),
        pa.array(["links", "links", "links", "links", "links"], type=pa.string()),
        pa.array([1.0, 1.0, 1.0, 1.0, 1.0], type=pa.float64()),
    ], names=["source", "target", "relation", "weight"])
    table.insert(data)
    table.commit()
    return table

def test_dbt_pagerank_sql(dbt_edge_table):
    """Verify SQL generated by {{ pagerank(ref('edges')) }} executes successfully."""
    # Rendered hyperstreamdb__pagerank macro SQL
    sql = "SELECT unnest(pagerank(source, target, arrow_cast(0.85, 'Float64'), arrow_cast(30, 'UInt32'))) FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "node" in res.columns
    assert "score" in res.columns

def test_dbt_personalized_pagerank_sql(dbt_edge_table):
    """Verify SQL generated by {{ personalized_pagerank(...) }} executes successfully."""
    # Without weights
    sql = "SELECT unnest(personalized_pagerank(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), make_array(arrow_cast(1, 'UInt64'), arrow_cast(2, 'UInt64')), arrow_cast(0.85, 'Float64'), arrow_cast(30, 'UInt32'), false)) FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "node" in res.columns
    assert "score" in res.columns

    # With HippoRAG seed weights
    sql_weighted = "SELECT unnest(personalized_pagerank(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), make_array(arrow_cast(1, 'UInt64'), arrow_cast(2, 'UInt64')), arrow_cast(0.85, 'Float64'), arrow_cast(30, 'UInt32'), false, make_array(arrow_cast(0.9, 'Float64'), arrow_cast(0.1, 'Float64')))) FROM t"
    res_w = dbt_edge_table.execute_sql(sql_weighted).to_pandas()
    assert not res_w.empty
    assert "node" in res_w.columns

def test_dbt_community_detect_sql(dbt_edge_table):
    """Verify SQL generated by {{ community_detect(...) }} executes successfully."""
    # Louvain
    sql_louvain = "SELECT unnest(louvain_communities(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), arrow_cast(1.0, 'Float32'), arrow_cast(1.0, 'Float32'))) as community FROM t"
    res = dbt_edge_table.execute_sql(sql_louvain).to_pandas()
    assert not res.empty
    assert "community" in res.columns

    # Label propagation
    sql_lp = "SELECT unnest(label_propagation(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'))) as community FROM t"
    res_lp = dbt_edge_table.execute_sql(sql_lp).to_pandas()
    assert not res_lp.empty
    assert "community" in res_lp.columns

def test_dbt_graph_neighbors_sql(dbt_edge_table):
    """Verify SQL generated by {{ graph_neighbors(...) }} executes successfully."""
    sql = "SELECT unnest(graph_neighbors(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), arrow_cast(1, 'UInt64'), arrow_cast(2, 'UInt32'))) as neighbor FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "neighbor" in res.columns

def test_dbt_subgraph_sql(dbt_edge_table):
    """Verify SQL generated by {{ subgraph(...) }} executes successfully."""
    sql = "SELECT unnest(subgraph(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), make_array(arrow_cast(1, 'UInt64')), arrow_cast(1, 'UInt32'), false)) FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "source" in res.columns
    assert "target" in res.columns

def test_dbt_shortest_path_sql(dbt_edge_table):
    """Verify SQL generated by {{ shortest_path(...) }} executes successfully."""
    sql = "SELECT unnest(shortest_path(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), arrow_cast(1, 'UInt64'), arrow_cast(4, 'UInt64'))) as node FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "node" in res.columns

def test_dbt_connected_components_sql(dbt_edge_table):
    """Verify SQL generated by {{ connected_components(...) }} executes successfully."""
    sql_wcc = "SELECT unnest(connected_components(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'))) as component FROM t"
    res_wcc = dbt_edge_table.execute_sql(sql_wcc).to_pandas()
    assert not res_wcc.empty

    sql_scc = "SELECT unnest(strongly_connected_components(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'))) as scc_id FROM t"
    res_scc = dbt_edge_table.execute_sql(sql_scc).to_pandas()
    assert not res_scc.empty

def test_dbt_degree_centrality_sql(dbt_edge_table):
    """Verify SQL generated by {{ degree_centrality(...) }} executes successfully."""
    sql = "SELECT unnest(degree_centrality(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'))) FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "node" in res.columns
    assert "degree" in res.columns

def test_dbt_node_similarity_sql(dbt_edge_table):
    """Verify SQL generated by {{ node_similarity(...) }} executes successfully."""
    sql = "SELECT jaccard_coefficient(arrow_cast(source, 'UInt64'), arrow_cast(target, 'UInt64'), arrow_cast(1, 'UInt64'), arrow_cast(3, 'UInt64')) as score FROM t"
    res = dbt_edge_table.execute_sql(sql).to_pandas()
    assert not res.empty
    assert "score" in res.columns

def test_dbt_macro_file_syntax():
    """Verify dbt macro SQL file contains valid Jinja syntax and all expected macro definitions."""
    import jinja2
    macro_path = "dbt-hyperstreamdb/dbt/include/hyperstreamdb/macros/graph.sql"
    with open(macro_path, "r") as f:
        content = f.read()
    env = jinja2.Environment()
    parsed = env.parse(content)
    assert parsed is not None
    for macro_name in [
        "pagerank", "personalized_pagerank", "community_detect",
        "graph_neighbors", "subgraph", "connecting_paths",
        "shortest_path", "connected_components", "degree_centrality",
        "node_similarity", "topological_sort"
    ]:
        assert macro_name in content
